# Generated by Django 2.2.1 on 2019-05-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_generate_password', 'Can generate password'), ('can_view_users', 'Can view users'), ('can_change_password', 'Can change password')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
