# Generated by Django 2.2.1 on 2019-05-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_view_companies', 'Can view companies'), ('can_assign_company', 'Can assign company')]},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_view_departments', 'Can view departments')]},
        ),
    ]
